### ISSUE TITLE
parse error in markbot 

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/animated-clock#1]
@anna-pokhilenko

markbot keeps saying it's line 51

**Comment by anna-pokhilenko** [comment]
<img width="385" alt="Screen Shot 2021-11-15 at 8 02 28 PM" src="https://user-images.githubusercontent.com/55008926/141876819-824e6685-72ec-4346-9de2-86785d1ec0a8.png">

You forgot to close the keyframe expression! 
Add a } at the end and the problem will be solved :)

**Comment by askaalyy** [comment]
thank you!
